### ISSUE TITLE
Runtime exception while executing bin\kshell.bat on Windows 10 Home

### ISSUE THREAD

**Issue by MinaevNM** [khud/sparklin#26]
C:\sparklin>java -classpath C:\Users\laval\.m2\repository\org\jetbrains\kotlin\kotlin-compiler\1.2.61\kotlin-compiler-1.2.61.jar;C:\Users\laval\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.2.61\kotlin-stdlib-1.2.61.jar;C:\Users\laval\.m2\repository\org\jetbrains\kotlin\kotlin-reflect\1.2.61\kotlin-reflect-1.2.61.jar;C:\Users\laval\.m2\repository\org\jetbrains\kotlin\kotlin-script-runtime\1.2.61\kotlin-script-runtime-1.2.61.jar;C:\Users\laval\.m2\repository\com\github\khud\kshell-repl-api\0.2.4-1.2.60\kshell-repl-api-0.2.4-1.2.60.jar;C:\Users\laval\.m2\repository\sparklin\kshell\0.2.4\kshell-0.2.4.jar; com.github.khud.sparklin.kshell.KotlinShell
WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
        at com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:82)
        at com.intellij.openapi.application.PathManager.findBinFile(PathManager.java:161)
        at com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:321)
        at com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
        at com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:62)
        at com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:54)
        at com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:61)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:43)
        at com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
        at com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:60)
        at com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:52)
        at com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:83)
        at com.intellij.openapi.vfs.impl.ZipHandler.acquireZipHandle(ZipHandler.java:129)
        at com.intellij.openapi.vfs.impl.ZipHandlerBase.createEntriesMap(ZipHandlerBase.java:44)
        at com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:197)
        at com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.lambda$new$0(CoreJarFileSystem.java:33)
        at com.intellij.util.containers.ConcurrentFactoryMap$4.create(ConcurrentFactoryMap.java:224)
        at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:63)
        at com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:44)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:398)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:377)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$contentRootToVirtualFile(KotlinCoreEnvironment.kt:117)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(KotlinCoreEnvironment.kt:255)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$5.invoke(KotlinCoreEnvironment.kt:117)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:262)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:117)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:446)
        at com.github.khud.kshell.repl.ReplChecker.<init>(ReplChecker.kt:42)
        at com.github.khud.kshell.repl.ReplCompiler.<init>(ReplCompiler.kt:21)
        at com.github.khud.sparklin.kshell.KShell.initEngine(KShell.kt:127)
        at com.github.khud.sparklin.kshell.KShell.doRun(KShell.kt:141)
        at com.github.khud.sparklin.kshell.KotlinShell.main(KotlinShell.kt:31)
kshell 0.2.4/1.2.61

**Comment by khud** [comment]
@MinaevNM, It is suppose to be fixed right now. Try it.
