### ISSUE TITLE
An exception thrown in `toString` should not quit the REPL

### ISSUE THREAD

**Issue by holgerbrandl** [khud/sparklin#28]
Example

```
 class Foo{
        override fun toString(): String {
            throw RuntimeException("something went wrong")
        }
    }

    Foo()
```

which results in 
```
[1] import java.lang.RuntimeException
[2] class Foo{
...        override fun toString(): String {
...            throw RuntimeException("something went wrong")
...        }
...    }
[7] Foo()
Exception in thread "main" java.lang.RuntimeException: something went wrong
	at Line_6$Foo.toString(Line_6.kt:5)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.github.khud.kshell.repl.EvalResult$ValueResult.toString(ReplApi.kt:23)
	at sparklin.kshell.KShell.handleSuccess(KShell.kt:241)
	at sparklin.kshell.KShell.doRun(KShell.kt:177)
	at sparklin.kshell.KotlinShell.main(KotlinShell.kt:31)

Bye!
[scripts]$ 
```

**Comment by khud** [comment]
Thanks a lot. I will fix it asap. Moreover I found https://github.com/khud/sparklin/issues/29
